language: node_js
node_js:
  - 8
  - 10
env:
  - secure: ""
deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    repo: Laboratoria/curricula-ux
    all_branches: true
